---
ID: "077d6245-4d34-5a2e-9ab4-7d8c7161db21"
Parent: "9b252ccb-cb6d-529a-b0db-5f9c46e8c001"
Template: "9b252ccb-cb6d-529a-b0db-5f9c46e8c001"
Path: "/sitecore/templates/Project/hardcore/Styleguide-FieldUsage-Date/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220305T034149Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "95d4fa5e-4549-43e2-93af-8891f6ae193a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220305T034149Z
