---
ID: "a92441a0-60b3-5fba-a3f3-fb4b6c67d550"
Parent: "43cc7fe0-aac7-5c58-a44a-8e39f24b83c5"
Template: "43cc7fe0-aac7-5c58-a44a-8e39f24b83c5"
Path: "/sitecore/templates/Project/hardcore/GraphQL-IntegratedDemo/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220305T034152Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cf08ebc9-970c-4a54-a028-49b5d647a3ff"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220305T034152Z
